### ISSUE TITLE
Use resource instead of guessing in seeker

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#41]
As @mitulgolakiya figured out here[#36 ](https://github.com/headlesslaravel/formations/issues/36#issuecomment-1014191011), seeker is guessing the resource for no reason. We should use the resource name defined in the routes file.

I will address this in a upcoming refactor

**Comment by mitulgolakiya** [comment]
@dillingham I was not able to use this code somehow,

`app(Manager::class)->resource($this->key)`

Because everything is now stored based on `key` which is a `resource` name. But here we need a resource name. so what I did is, I created another method in `Manager` which returns the resource by the formation class.

But please note that, if the same formation class is registered twice with a different resource name, then it will use the first one that is found in the array.

**Comment by dillingham** [comment]
@mitulgolakiya ah yeah I see how my original idea was flawed now. Thanks for catching that and making it clear.

I might need to refactor the general idea in the future.

But for now this is a very specific edge case Im wont experience and unblocks #51 

This works great for now thank you.
