### ISSUE TITLE
Imports: Duplicates in file

### ISSUE THREAD

**Issue by dillingham** [headlesslaravel/formations#70]
When uploading duplicates in the same file it doesnt pickup uniqueness

It should fail if you set the validation rule on a field to `unique:categories,title`, and submit the following

| title |
|-----|
| tech |
| tech |

### Task

- 1: Lets create a new .csv file with some duplicates in tests/Fixtures/with-unique-rule-and-duplicates.csv
- 2: Make a test that asserts only 1 model is created
- 3: Make the test pass by figuring out Import.php

**Comment by mitulgolakiya** [comment]
@dillingham The problem I found is, whenever we use [WithValidation](https://docs.laravel-excel.com/3.1/imports/validation.html) Interface, the Excel package does that validation based on defined rules function. But it does a validation before it creates all actual records. so unique validation doesn't make sense there. If we want to do that validation, then we need to do it at the time of creating records.

What I did is, I tried to use its inbuilt [RowValidator](https://github.com/headlesslaravel/formations/pull/72/files#diff-6cdc88386d94f12b64cabab9ef3c256e73478e674c88847a9bfa56d1fbd0db33R42) which is used by the Excel package itself.

The only problem with the current PR that I was not able to resolve is, at the moment, validation is happening twice. Once when excel prepares the rows and another when actual data is inserted into the database. To remove that, we need to remove `WithValidation` trait, but if we remove that then we are not able to use `RowValidator`anymore, since it requires an instance of `WithValidation` [here](https://github.com/SpartnerNL/Laravel-Excel/blob/3.1/src/Validators/RowValidator.php#L34).

**Comment by dillingham** [comment]
@mitulgolakiya thank you for the explanation. Very helpful. And nice PR!

That is a clever approach.. and a tricky problem since they typehint that method 🤔 I was trying to think of ways around it like extending the class but nothing comes to mind right now.. I'll keep thinking though.

Another approach I was thinking was checking all the rules for `unique` and doing some work around then in PHP only. I think per row is nice but if we can avoid sql queries per model then thats a bonus (although I guess its validating the entire file upfront and performing those queries currently?) I also just found the `distinct` rule [here](https://laravel.com/docs/8.x/validation#rule-distinct) maybe that is part of the solution somehow.

**Comment by dillingham** [comment]
I tested it with `distinct` and it worked, this is solved.
